export const WEATHER_ICONS_MAP: Record<string, string> = {
  '01d': 'sunny',
  '01n': 'dark_mode',
  '02d': 'cloud',
  '02n': 'cloud',
  '03d': 'cloud',
  '03n': 'cloud',
  '04d': 'cloud',
  '04n': 'cloud',
  '09d': 'rainy',
  '09n': 'rainy',
  '10d': 'rainy',
  '10n': 'rainy',
  '11d': 'thunderstorm',
  '11n': 'thunderstorm',
  '13d': 'ac_unit',
  '13n': 'ac_unit',
  '50d': 'foggy',
  '50n': 'foggy',
};
